apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.webapp.appName }}-svc
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.webapp.appName }}
spec:
  selector:
    app: {{ .Values.webapp.appName }}
  type: LoadBalancer
  ports:
    - name: http
      port: {{ .Values.webapp.service.port }}
      targetPort: 5000
      protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.appName }}-svc
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.db.appName }}
spec:
  selector:
    app: {{ .Values.db.appName }}

  type: NodePort
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
      protocol: TCP


---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.cache.appName }}-svc
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.cache.appName }}
spec:
  selector:
    app: {{ .Values.cache.appName }}

  type: NodePort
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
      protocol: TCP

