apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.volume.name }}

spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  storageClassName: standard
  hostPath:
    path: {{ .Values.volume.path }}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.db.deployment.volume.pvc.name }}

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
  volumeName: {{ .Values.volume.name }}

